# Site settings
title: Stop Motion Photo | Personal sports photography | Southern New England
email: chris@stopmophoto.com
description: > # this means to ignore newlines until "baseurl:"
  Personal sports photography for Southern New England
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.stopmophoto.com" # the base hostname & protocol for your site
twitter_username: stopmotionphoto

# Build settings
markdown: kramdown

exclude: ['vendor']
